### ISSUE TITLE
UI Fixes / Enhancements

### ISSUE THREAD

**Issue by boswelja** [DominionOS/packages_apps_Music#14]
- [x] The FAB for "Currently Playing" is awkwardly coloured. I know this might be a design decision, so I'll let this one pass for now
- [x] The icon for "Currently Playing" in the FAB looks like it's in low(er) resolution, I suggest using VectorDrawable or vectored icon
- [x] Some album returns empty or blank name
- [x] Song number greater than single digit (>9) wraps around awkwardly
- [x] In the now playing notification, the icon is in low resolution (same issue as the FAB)
- [x] Layout issues in Now Playing screen on some album (it mostly happens if the album has white coloured card in the "Albums" screen)
- [x] Why do we have a weird "Music" text overlaying the album art?
- [x] Ellipsis ("…") should be used if the album name can't be fit into the album card. Cutting them suddenly like the current implementation makes it looks rather bad (to be honest)
- [x] Swiping notification away shouldn't kill the app if I'm in the app - **Moved to a separate issue**
- [x] There's some weird blue/red mashup colour all over the place which doesn't seem to fit the colour palette
- [x] It'll be nice if the timer (the "how long the song has been playing and how long the song actually is") in the Now Playing screen has a shadow to make it a bit more readable in light coloured album art
- [x] The progress slider has its ripple effect cut weirdly
- [x] Song max durations ending in 0 have the 0 cut off
- [x] Overhaul add to playlist dialog

**Comment by boswelja** [comment]
Err, GItHub auto-closed this :/

**Comment by boswelja** [comment]
Once all these are checked off, I'll post a new build (With a version increment ofc)

**Comment by F4uzan** [comment]
Dang, you are fast. I was just about going to send a pull request for 3 and 14, but I guess it worked out well. I'll test the commits soon :)

**Comment by boswelja** [comment]
@F4uzan can you explain what you meant with number 8?

**Comment by F4uzan** [comment]
@boswelja basically, I can't seem to find a way to open the "Now Playing" screen other than using the notification and the "audiotrack" FAB. I could be wrong, but this makes it very intuitive, if I want to view the song I'm currently playing, I would need to either go to the main screen, or I would need to swipe down notification and tap it.

**Comment by boswelja** [comment]
@F4uzan what if we moved it from the FAB to the nav drawer?

**Comment by F4uzan** [comment]
Aha! Since we don't have the nav drawer header, why don't we reuse it and make it as a place to enter the Now Playing screen?

**Comment by boswelja** [comment]
@F4uzan the nav drawer header? Would newbies be able to work that out?

**Comment by F4uzan** [comment]
Yeah, actually, that'll make things complex for the average joe...

**Comment by boswelja** [comment]
Any other ideas?

**Comment by F4uzan** [comment]
I'll think of it as I go, for now all I can think of is navigation drawer.

**Comment by boswelja** [comment]
@F4uzan What if we had a bar at the bottom of the main view that had some basic details about the currently playing song?
 (Wouldn't be a sliding panel as that would require a rewrite of the player activity, service, and main activity)
