### ISSUE TITLE
No work ;--;

### ISSUE THREAD

**Issue by nearcbw** [DominionOS/packages_apps_Music#2]
![screenshot_2016-12-07-09-39-12](https://cloud.githubusercontent.com/assets/13632826/20968044/2168ab74-bc61-11e6-8f09-a13c403f0475.png)

**Comment by boswelja** [comment]
By any chance, are you running lollipop? If so, I have already fixed this issue and I can upload a build :)

**Comment by boswelja** [comment]
Can you try the latest build [HERE ](https://github.com/DominionOS/packages_apps_Music/releases)and let me know what happens?

**Comment by nearcbw** [comment]
working now.
