### ISSUE TITLE
Rewrite notifications

### ISSUE THREAD

**Issue by boswelja** [DominionOS/packages_apps_Music#25]
The entire notification code is using deprecated methods, it will need to be converted to a MediaStyle notification

**Comment by boswelja** [comment]
@F4uzan u wanna fix notifications?

**Comment by F4uzan** [comment]
I tried, not much of a progress due to life nowadays, I'll just take in the time to revamp some of the UI again, haha

**Comment by boswelja** [comment]
This is nearly done, I just need to make it load the album art into the notification
