### ISSUE TITLE
All visualizers do not render anything when music is playing from this app

### ISSUE THREAD

**Issue by boswelja** [DominionOS/packages_apps_Music#3]

**Comment by boswelja** [comment]
@F4uzan any idea what might be causing this? Its currently my top unsolvable issue :/

**Comment by F4uzan** [comment]
I'm stumped with this too, I have tried nearly everything in my head. Though that's not to say I don't have anymore ideas.

**Comment by boswelja** [comment]
Apparently it now works fine :/
